baseURL = "http://jmg-duarte.github.io/"
languageCode = "en-us"
title = "José Duarte"
theme = "cactus"

[params]
  colortheme="white"
  mainSection="posts"
  # showAllPostsOnHomePage = true
  mathjax = true

[[params.social]]
  name = "github"
  link = "https://github.com/jmg-duarte"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

# Basic Theme Params
# [[params.menu]]
#   name = "blog"
#   url = "posts/"

# [[params.menu]]
#   name = "about"
#   url = "about/"

# [privacy]
#   [privacy.googleAnalytics]
#     anonymizeIP = true
#     respectDoNotTrack = true
#     useSessionStorage = true
#   [privacy.twitter]
#     enableDNT = true
#   [privacy.youtube]
#     privacyEnhanced = true